### PR TITLE
Add unitfile to run plugin

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar lsm5@fedoraproject.org

ping @runcom @rhatdan

### CODE REVIEW

**Comment by lsm5** [comment]
added `Requires=docker.service` and `Before=docker.service`. PTAL

**Comment by lsm5** [comment]
description updated, PTAL.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by runcom** [comment]
LGTM

**Pull request merged**
